### ISSUE TITLE
Error when launching Fake Mailer

### ISSUE THREAD

**Issue by Sgroove** [htr-tech/fake-mailer#1]
Getting the following error when launching the mailer:
Launching Fake Mailer ...

Traceback (most recent call last):
  File "mailer.py", line 262, in <module>
    .split("  ")])))
  File "<string>", line 35, in <module>
NameError: name 'raw_input' is not defined

Any help?

**Comment by htr-tech** [comment]
### @Sgroove Follow The Installation Commands
### Installation :
apt update
apt install git -y
git clone https://github.com/htr-tech/fake-mailer
cd fake-mailer
bash setup
#### Run : python2 mailer.py
![image](https://user-images.githubusercontent.com/56682134/79112605-bd285d80-7da0-11ea-9245-ac40360c52b3.png)
### There is no Problem in The Codes

**Comment by icrookflip** [comment]
Error2 when trying to access file

└─[~]────►bash python2 mailer.py
/data/data/com.termux/files/usr/bin/python2: /data/data/com.termux/files/usr/bin/python2: cannot execute binary file
┌─[08:22:18]─────[root]───[4]
