### ISSUE TITLE
Obfuscated ?

### ISSUE THREAD

**Issue by OXDBXKXO** [htr-tech/fake-mailer#5]
Hi,
For those worried about the obfuscated setup script, it is safe. I made a script to reverse the base64-encoding. I don't really get why a script that simple was obfuscated, but OK. It's actually quite dumb as I'm on Arch so apt is not working for me and I could have fix the setup myself if the script were readable. Why the fuck do you share code on Github if you obfuscate it ? You don't get the point of open-source my friend ;)
For the main python script, as it calls pre-compiled code, it is not possible to access code-source. I advise everyone NOT to use this tool. Creating an anonymous mailer is trivial and it is very suspicious that the code is obfuscated as it was some cutting-edge technology. If you do not know what you doing, you may be causing harm to your device

**Comment by htr-tech** [comment]
@OXDBXKXO Check dude :V
