### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ritz541** [htr-tech/fake-mailer#6]
Whe we submit all the credentials and press enter nothing happens.

**Comment by htr-tech** [comment]
@ritz541 sry bro 😭 

use this website http://anonymouse.org/anonemail.html

**Comment by ritz541** [comment]
> @ritz541 sry bro 😭 
> 
> use this website http://anonymouse.org/anonemail.html

Ok I'll see later

**Comment by ritz541** [comment]
> @ritz541 sry bro 😭 
> 
> use this website http://anonymouse.org/anonemail.html

Thankd for reply
